project:
  type: website
  output-dir: docs

website:
  title: "Cardiac T1 and T2 Mapping at 1.5T"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - stats.qmd
      - aim1.qmd
      - aim2.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

